//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum LyricsRestriction: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case unrestricted // = 0
  case showLyrics // = 1
@@ -69,22 +69,22 @@ extension LyricsRestriction: CaseIterable {
#endif  // swift(>=4.2)

struct LyricsLine {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var offsetMs: Int32 = 0

  var content: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct LyricsColors {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var backgroundColor: UInt32 = 0
@@ -93,28 +93,28 @@ struct LyricsColors {

  var activeLineColor: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct LyricsTranslation {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var languageCode: String = String()

  var lines: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct LyricsData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var timeSynchronized: Bool = false
@@ -134,16 +134,16 @@ struct LyricsData {
  /// Clears the value of `translation`. Subsequent reads from it will return its default value.
  mutating func clearTranslation() {self._translation = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _translation: LyricsTranslation? = nil
}

struct Lyrics {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var data: LyricsData {
@@ -164,7 +164,7 @@ struct Lyrics {
  /// Clears the value of `colors`. Subsequent reads from it will return its default value.
  mutating func clearColors() {self._colors = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

@@ -181,25 +181,25 @@ extension LyricsData: @unchecked Sendable {}
extension Lyrics: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension LyricsRestriction: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNRESTRICTED"),
    1: .same(proto: "SHOW_LYRICS"),
    2: .same(proto: "SHOW_LYRICS_MONTHLY_LIMIT"),
    3: .same(proto: "MONTHLY_LIMIT_REACHED"),
  ]
}

extension LyricsLine: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LyricsLine"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "offsetMs"),
    2: .same(proto: "content"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
@@ -212,7 +212,7 @@ extension LyricsLine: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementatio
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.offsetMs != 0 {
      try visitor.visitSingularInt32Field(value: self.offsetMs, fieldNumber: 1)
    }
@@ -230,15 +230,15 @@ extension LyricsLine: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementatio
  }
}

extension LyricsColors: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LyricsColors"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "backgroundColor"),
    2: .same(proto: "lineColor"),
    3: .same(proto: "activeLineColor"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
@@ -252,7 +252,7 @@ extension LyricsColors: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementat
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.backgroundColor != 0 {
      try visitor.visitSingularUInt32Field(value: self.backgroundColor, fieldNumber: 1)
    }
@@ -274,14 +274,14 @@ extension LyricsColors: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementat
  }
}

extension LyricsTranslation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LyricsTranslation"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "languageCode"),
    2: .same(proto: "lines"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
@@ -294,7 +294,7 @@ extension LyricsTranslation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplem
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.languageCode.isEmpty {
      try visitor.visitSingularStringField(value: self.languageCode, fieldNumber: 1)
    }
@@ -312,17 +312,17 @@ extension LyricsTranslation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplem
  }
}

extension LyricsData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LyricsData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "timeSynchronized"),
    2: .same(proto: "lines"),
    5: .same(proto: "providedBy"),
    14: .same(proto: "restriction"),
    9: .same(proto: "translation"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
@@ -338,7 +338,7 @@ extension LyricsData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementatio
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
@@ -372,14 +372,14 @@ extension LyricsData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementatio
  }
}

extension Lyrics: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Lyrics"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "data"),
    2: .same(proto: "colors"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
@@ -392,7 +392,7 @@ extension Lyrics: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBas
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
